export const [
  CHILL_STATUS_NONE,
  CHILL_STATUS_PENDING,
  CHILL_STATUS_SUCCESS,
  CHILL_STATUS_FAILURE
] = [
  "CHILL_STATUS_NONE",
  "CHILL_STATUS_PENDING",
  "CHILL_STATUS_SUCCESS",
  "CHILL_STATUS_FAILURE"
]