
export default {
  TOGGLE_CHILLER_SELECT : 'TOGGLE_CHILLER_SELECT',
  CHILL_REQUESTED: 'CHILL_REQUESTED',
  CHILL_SUCCESS: 'CHILL_SUCCESS' ,
  CHILL_FAILURE: 'CHILL_FAILURE',
  GET_CONTACTS_REQUESTED: 'GET_CONTACTS_REQUESTED',
  GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
  GET_CONTACTS_FAILURE: 'GET_CONTACTS_FAILURE',
} 